
try:

    print(a)
except Exception as e:
    print("Something went wrong please try again later") # handle error in code to avoid breaking our code
